### ISSUE TITLE
Incorporate the non-profit "Our Data Our Hands"

### ISSUE THREAD

**Issue by ivanstegic** [ourdataourhands/nonprofit#1]
We have to actually incorporate the organization as an entity. Andrew's agreed to take this on. I suggest that the three founding members be Andrew WH, James R and Ivan S. This is not for the paperwork to actually create the tax exempt 501.

**Comment by andrewkwh** [comment]
I'm breaking this into two small steps. First part will be the basic incorporation paperwork. One of the key items to address is the physical address. I will discuss that with James. The second item is the actual bylaws. I have a basic framework ready, but I think we should discuss in person - perhaps this upcoming Sunday?

**Comment by 20zinnm** [comment]
Sure. Also, what's our license for everything? I'm comfortable licensing my stuff under MIT or Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0).

**Comment by ivanstegic** [comment]
@andrewkwh did this! https://github.com/ourdataourhands/nonprofit/wiki/Articles-of-Incorporation
